# Generated by Django 2.2.6 on 2019-10-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_auto_20191026_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='payee',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
