# Generated by Django 2.2.6 on 2019-10-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_auto_20191026_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='payee',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
