# Generated by Django 2.2.6 on 2019-10-26 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_auto_20191026_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=None, to='budgets.Budget'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 26, 20, 52, 5, 395343, tzinfo=utc)),
        ),
    ]
