# Generated by Django 2.2.6 on 2019-10-26 21:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_auto_20191026_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 26, 21, 30, 31, 71985, tzinfo=utc)),
        ),
    ]
