# Generated by Django 2.2.6 on 2019-10-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_auto_20191026_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
