# Generated by Django 2.2.6 on 2019-10-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0010_target_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
