# Generated by Django 2.2.6 on 2019-11-02 20:39

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0011_auto_20191029_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='payee',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorful.fields.RGBColorField(default='#2d4d80'),
        ),
        migrations.AlterField(
            model_name='item',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='budgets.Budget'),
        ),
    ]
